/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.garrafa.térmica.Telas;

import projeto.garrafa.térmica.GarrafaTermica;
import java.text.DecimalFormat; 
import java.util.ArrayList;

/**
 *
 * @author Casa
 */
public class TelaAnaliseTemp extends javax.swing.JFrame {
    
   
    /**
     * Creates new form TelaResultado
     */
    
 
     
   
    
    public TelaAnaliseTemp() {
        initComponents();
        setTitle("Garrafa Termica");
        setSize(550, 360);
        setLocationRelativeTo(null); 
        setResizable(false); 
        setVisible(true);
    }
    
    DecimalFormat df = new DecimalFormat("0.#");
    double c;
    
    TelaAnaliseTemp(double tempoinicial) {
        initComponents();
        setTitle("Garrafa Termica");
        setSize(550, 360);
        setLocationRelativeTo(null); 
        setResizable(false); 
        setVisible(true);
        
       
        
    
        
 
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        botao_voltar = new javax.swing.JButton();
        temperatura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tempofinal = new javax.swing.JLabel();
        tempo = new javax.swing.JLabel();
        campo_tempo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Decaimento Da Temperatura ");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 480, -1));

        botao_voltar.setText("Voltar");
        botao_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_voltarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(botao_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        temperatura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        temperatura.setText("LISTA");
        temperatura.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                temperaturaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jInternalFrame1.getContentPane().add(temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, 120));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TEMPERATURA");
        jInternalFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TEMPO");
        jInternalFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 160, -1));

        tempofinal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tempofinal.setText("tem");
        jInternalFrame1.getContentPane().add(tempofinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 90, 20));

        tempo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tempo.setText("LISTA");
        jInternalFrame1.getContentPane().add(tempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 220, 140));

        campo_tempo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        campo_tempo2.setText("Tempo Final:");
        jInternalFrame1.getContentPane().add(campo_tempo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        // TODO add your handling code here:
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
           
        dispose();
    }//GEN-LAST:event_botao_voltarActionPerformed

    private void temperaturaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_temperaturaAncestorAdded
        // TODO add your handling code here:
        ArrayList<Integer> info = new ArrayList();
        for (int i=0; i<5; i++) {
        info.add(i);
        temperatura.setText(info.toString());
    }
        
        
    }//GEN-LAST:event_temperaturaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnaliseTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnaliseTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnaliseTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnaliseTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAnaliseTemp().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_voltar;
    private javax.swing.JLabel campo_tempo2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel temperatura;
    private javax.swing.JLabel tempo;
    private javax.swing.JLabel tempofinal;
    // End of variables declaration//GEN-END:variables
}
