package projeto.garrafa.térmica.Telas;

import javax.swing.JOptionPane;
import projeto.garrafa.térmica.GarrafaTermica;

public class TelaInicial extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        
        initComponents();
        setTitle("Garrafa Termica");
        setSize(550, 360);
        setLocationRelativeTo(null); 
        setResizable(false); 
        setVisible(true);
       
    }

    
    public String aM,am,dM,dm = null;
     
    TelaInicial(String alturaM, String alturam, String diaM, String diam) {
        
        initComponents();
        setTitle("Garrafa Termica");
        setSize(550, 360);
        setLocationRelativeTo(null); 
        setResizable(false); 
        setVisible(true);
        
        this.aM = alturaM ;
        this.am = alturam ;
        this.dM = diaM ;
        this.dm = diam ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel_TemperaturaInicial = new javax.swing.JLabel();
        campo_TemperaturaInicial = new javax.swing.JTextField();
        jLabel_Liquido = new javax.swing.JLabel();
        campo_liquido = new javax.swing.JComboBox<>();
        botao_calcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botao_informacao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Vaso Dewar");

        jLabel_TemperaturaInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_TemperaturaInicial.setText("Temperatura Inicial:");

        campo_TemperaturaInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campo_TemperaturaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_TemperaturaInicialActionPerformed(evt);
            }
        });

        jLabel_Liquido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Liquido.setText("Liquido:");

        campo_liquido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campo_liquido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua", "Alcool", "Gelo" }));

        botao_calcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_calcular.setText("Calcular");
        botao_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_calcularActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/garrafa/térmica/Telas/Garrafa.png"))); // NOI18N

        botao_informacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao_informacao.setText("Configurações Garrafa");
        botao_informacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_informacaoActionPerformed(evt);
            }
        });

        jLabel3.setText("ºC");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botao_calcular)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_TemperaturaInicial)
                                .addComponent(jLabel_Liquido))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campo_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(campo_TemperaturaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3))))
                        .addComponent(botao_informacao)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(8, 12, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TemperaturaInicial)
                    .addComponent(campo_TemperaturaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Liquido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_calcular)
                .addGap(18, 18, 18)
                .addComponent(botao_informacao)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_calcularActionPerformed
        // TODO add your handling code here:
        String temperaturainicial = campo_TemperaturaInicial.getText();
        String liquido = campo_liquido.getSelectedItem().toString();
        
        if(temperaturainicial.equals("")  ){
           JOptionPane.showMessageDialog(null, "Preencha o campo da temperatura inicial!!", "Aviso",JOptionPane.INFORMATION_MESSAGE);
           
        } else  {
            
            if(aM != null){
                TelaResultado telaResul = new TelaResultado(aM,am,dM,dm, liquido,Double.parseDouble(temperaturainicial));
                telaResul.setVisible(true);
                
            }else{
                TelaResultado telaResul = new TelaResultado(liquido, Double.parseDouble(temperaturainicial));
                telaResul.setVisible(true);
            }
           
            dispose();
        }
        
    }//GEN-LAST:event_botao_calcularActionPerformed

    private void campo_TemperaturaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_TemperaturaInicialActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campo_TemperaturaInicialActionPerformed

    private void botao_informacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_informacaoActionPerformed
        // TODO add your handling code here:
        TelaConfiguracaoGarrafa telaconfGarrafa = new TelaConfiguracaoGarrafa();
        telaconfGarrafa.setVisible(true);

        dispose();
    }//GEN-LAST:event_botao_informacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_calcular;
    private javax.swing.JButton botao_informacao;
    private javax.swing.JTextField campo_TemperaturaInicial;
    private javax.swing.JComboBox<String> campo_liquido;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Liquido;
    private javax.swing.JLabel jLabel_TemperaturaInicial;
    // End of variables declaration//GEN-END:variables
}
